[package]
name = "prime_number"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prime_tools = "0.3.4"
rand = "0.8.4"
rug = "1.12.0"