[package]
name = "Pixels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
image = "0.23.14"
num = "0.4.0"
num_cpus = "1.13.0"
threadpool = "1.8.1"
rayon = "1.5.1"