[package]
name = "A3T2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hamcrest = "0.1.5"

[dev-dependencies]
hamcrest = "*"

